### ISSUE TITLE
Implement tendermint lite client commands

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer-archive#1]
There are currently a series of commands in `cmd/lite.go` that need to be implemented. The logic should be implemented in `relayer/verifier.go` and then wired up to the CLI in `cmd/lite.go`.

cc @melekes

**Comment by melekes** [comment]
cc @cmwaters

**Comment by cmwaters** [comment]
Anton and I discussed the cli interface and proposed the following changes:

- Merge the Init and Update Cmd to a start command because they almost do the same thing.

- Add a getHeader and getValidatorSet command which takes the height as an argument and returns the header and validator respectively. This can be used to confirm that what has been relayed is now in the other blockchain.

**Comment by melekes** [comment]
I propose the following sub-commands:

```
lite reset [chainID] --trusted-hash=0xaaabbb --trusted-height=1
lite reset [chainID] --url https://xyz.com
lite delete [chainID]

lite header chainID # returns latest header without params
lite header chainID 1 # returns header at height 1 (if stored)
lite header chainID -1 # returns first stored header

lite vals chainID # returns latest validator set without params
lite vals chainID 1 # returns validator set at height 1 (if stored)
lite vals chainID -1 # returns first stored validator set
```

**Comment by melekes** [comment]
Q: 

1) do we need `lite stop` and `lite delete` sub-commands? What's the point of stopping the light client? maintenance? 
2) should `lite stop` also delete all the data? What's the point of having a separate command?

My opinion:
we don't need stop (for now) but delete is required because process can crash and the user will need to manually delete the data sometimes.

**Comment by jackzampolin** [comment]
@melekes agreed with removing `stop` and adding `delete`. Like the `lite get-header` and `lite get-valset`. Would be nice if you could also use that to query for the roots of trust too.

**Comment by melekes** [comment]
Update the list of sub-commands: https://github.com/cosmos/relayer/issues/1#issuecomment-577582199

**Comment by melekes** [comment]
> Would be nice if you could also use that to query for the roots of trust too.

that's what `lite header` is for

**Comment by jackzampolin** [comment]
@melekes @cmwaters really enjoyed working with y'all on this. Going to close this issue as complete!
